#!/bin/bash

ADDR=${1-auto}

if [ "$ADDR" == "auto" ]; then
	echo "Autodetecting i²c address..."
	for a in 14 5d; do
		echo "Testing address $a..."
		scan=$(i2cdetect -y 11 "0x$a" "0x$a" | tail -n +2 | cut -d' ' -f2-)
		case $scan in
			*"--"*)
				echo "  - Unused."
			;;
			*"UU"*)
				echo "  - Address busy. Probably in use by driver."
			;;
			*"$a"*)
				echo "  - Address available. Using."
				ADDR=$a
				break
			;;
		esac
	done
fi

if [ "$ADDR" == "auto" ]; then
	echo "Could not find i²c address. Exiting." >&2
	exit 1
fi

# sed "s/{ADDR}/${ADDR}/" hypertouch40.dts.template > hypertouch40.dts
sed "s/{ADDR}/${ADDR}/" hypertouch40.dts.template | dtc -I dts -O dtb -o /boot/overlays/hypertouch40.dtbo -
